python qlora.py \
    --model_name_or_path /hdd4/zoo/llama2/llama2-7b-hf \
    --use_auth \
    --output_dir /hdd3/mohammed/llama_qlora/ckpts/ \
    --logging_steps 10 \
    --save_strategy steps \
    --data_seed 42 \
    --save_steps 5 \
    --save_total_limit 40 \
    --evaluation_strategy steps \
    --eval_dataset_size 1 \
    --max_eval_samples 1 \
    --per_device_eval_batch_size 1 \
    --max_new_tokens 190 \
    --dataloader_num_workers 1 \
    --group_by_length \
    --logging_strategy steps \
    --remove_unused_columns False \
    --do_train True \
    --eval_samples True \
    --do_mmlu_eval False \
    --diversity False \
    --divdist manhattan \
    --lora_r 64 \
    --lora_alpha 16 \
    --lora_modules all \
    --double_quant \
    --quant_type nf4 \
    --bf16 \
    --bits 4 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type constant \
    --gradient_checkpointing \
    --dataset /hdd3/mohammed/llama_qlora/llama_format_feb27.dat \
    --source_max_len 16 \
    --target_max_len 512 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --max_steps 60 \
    --eval_steps 1 \
    --learning_rate 0.0002 \
    --adam_beta2 0.999 \
    --max_grad_norm 0.3 \
    --lora_dropout 0.1 \
    --weight_decay 0.0 \
    --seed 0 
    
