python qlora.py \
    --model_name_or_path /mnt/data/zoo/llama2/llama2-7b-hf/ \
    --use_auth \
    --logging_steps 1 \
    --save_strategy steps \
    --data_seed 42 \
    --save_steps 2 \
    --save_total_limit 4000 \
    --evaluation_strategy steps \
    --eval_dataset_size 1 \
    --max_eval_samples 1 \
    --per_device_eval_batch_size 1 \
    --max_new_tokens 32 \
    --dataloader_num_workers 1 \
    --group_by_length \
    --logging_strategy steps \
    --remove_unused_columns False \
    --do_train \
    --do_eval \
    --eval_samples \
    --lora_r 64 \
    --lora_alpha 16 \
    --lora_modules all \
    --double_quant \
    --quant_type nf4 \
    --bf16 \
    --bits 8 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type constant \
    --gradient_checkpointing \
    --dataset /mnt/data/sonia/honeygan/llama_format_jul25.dat \
    --source_max_len 16 \
    --target_max_len 512 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --max_steps 20 \
    --seed 0 \
    --eval_steps 5 \
    --adam_beta2 0.999 \
    --max_grad_norm 0.3 \
    --lora_dropout 0.1 \
    --output_dir /mnt/data/sonia/ckpts/debug \
    --learning_rate 0.02 \
    --weight_decay 0 \
